import { createClient } from '@supabase/supabase-js';
import { NextResponse } from 'next/server';
import OpenAI from 'openai';
import { logClinicalAction } from '@/lib/audit';

const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

const LAB_SYSTEM_PROMPT = `You are a clinical laboratory analysis assistant.

You will receive structured numerical lab values from a patient.
Your task is to:
1. Interpret each value against standard clinical reference ranges.
2. Identify any abnormalities (Normal/Low/High/Critical).
3. Calculate an overall metabolic risk score from 0-100.
4. Provide a concise, factual clinical summary.

SAFETY & COMPLIANCE (PHASE 8):
- You are an ANALYSIS SUPPORT TOOL ONLY. Not a substitute for professional medical judgment.
- Do NOT recommend specific medications or prescribe treatments.
- Only include values that were actually provided (not "N/A" values).
- Be strictly factual, objective, and clearly flag any critical values.

Return ONLY valid JSON with no markdown or code blocks:
{
  "risk_score": <number 0-100>,
  "risk_level": "<Low|Medium|High|Critical>",
  "summary": "<2-3 sentence objective clinical summary>",
  "interpretations": [
    {
      "metric": "<metric name>",
      "value": "<value with unit>",
      "status": "<Normal|Low|High|Critical>",
      "insight": "<one sentence factual clinical note>"
    }
  ],
  "recommendations": ["<clinical observation 1>", "<clinical observation 2>"],
  "disclaimer": "Results generated by AI. Must be reviewed by a qualified clinician before any clinical decision."
}`;

export async function POST(request) {
  try {
    // Session validation — Bearer token pattern (consistent with all other API routes)
    const supabase = createClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL,
      process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY
    );

    const { data: { user }, error: authError } = await supabase.auth.getUser(
      request.headers.get('Authorization')?.split(' ')[1]
    );

    if (authError || !user) {
      return NextResponse.json({ error: 'Unauthorized: Clinical session required.' }, { status: 401 });
    }

    const body = await request.json();
    const { systolic, diastolic, glucose, hba1c, cholesterol, ldl, hdl, triglycerides } = body;

    // Validate — at least one value must be provided
    const values = [systolic, diastolic, glucose, hba1c, cholesterol, ldl, hdl, triglycerides];
    if (values.every(v => !v || String(v).trim() === '')) {
      return NextResponse.json({ error: 'At least one lab value is required.' }, { status: 400 });
    }

    // Build clinical text — only include provided values
    const labLines = [
      systolic && diastolic ? `Blood Pressure: ${systolic}/${diastolic} mmHg` : null,
      systolic && !diastolic ? `Systolic BP: ${systolic} mmHg` : null,
      glucose ? `Fasting Blood Glucose: ${glucose} mg/dL` : null,
      hba1c ? `HbA1c: ${hba1c}%` : null,
      cholesterol ? `Total Cholesterol: ${cholesterol} mg/dL` : null,
      ldl ? `LDL Cholesterol: ${ldl} mg/dL` : null,
      hdl ? `HDL Cholesterol: ${hdl} mg/dL` : null,
      triglycerides ? `Triglycerides: ${triglycerides} mg/dL` : null,
    ].filter(Boolean);

    const labText = `Patient Laboratory Values:\n${labLines.join('\n')}`;

    // Call OpenAI Neural Engine
    const completion = await openai.chat.completions.create({
      model: 'gpt-4o',
      messages: [
        { role: 'system', content: LAB_SYSTEM_PROMPT },
        { role: 'user', content: labText }
      ],
      response_format: { type: 'json_object' },
      temperature: 0.2
    });

    let analysis;
    try {
      analysis = JSON.parse(completion.choices[0].message.content);
    } catch {
      throw new Error('Neural Engine returned malformed JSON. Please try again.');
    }

    // Phase 8: Clinical Audit
    await logClinicalAction(user.id, 'lab_analysis');

    return NextResponse.json({ success: true, analysis });

  } catch (error) {
    console.error('Lab Analyzer API Error:', error.message);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
